export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";
export const ORDER_CREATE_RESET = "ORDER_CREATE_RESET";

export const ORDER_GETMINE_REQUEST = "ORDER_GETMINE_REQUEST";
export const ORDER_GETMINE_SUCCESS = "ORDER_GETMINE_SUCCESS";
export const ORDER_GETMINE_FAIL = "ORDER_GETMINE_FAIL";

export const ORDER_GETALL_REQUEST = "ORDER_GETALL_REQUEST";
export const ORDER_GETALL_SUCCESS = "ORDER_GETALL_SUCCESS";
export const ORDER_GETALL_FAIL = "ORDER_GETALL_FAIL";

export const ORDER_UPDATE_REQUEST = "ORDER_UPDATE_REQUEST";
export const ORDER_UPDATE_SUCCESS = "ORDER_UPDATE_SUCCESS";
export const ORDER_UPDATE_FAIL = "ORDER_UPDATE_FAIL";
export const ORDER_UPDATE_RESET = "ORDER_UPDATE_RESET";

export const ORDER_DELETE_REQUEST = "ORDER_DELETE_REQUEST";
export const ORDER_DELETE_SUCCESS = "ORDER_DELETE_SUCCESS";
export const ORDER_DELETE_FAIL = "ORDER_DELETE_FAIL";
export const ORDER_DELETE_RESET = "ORDER_DELETE_RESET";

export const SET_ORDER = "SET_ORDER";
